version: '3.8'

services:
  db:
    container_name: db
    image: postgres:16.3-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  migration:
    container_name: migration
    build:
      context: .
      dockerfile: Dockerfile
      target: migrations
    depends_on:
      - db

  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db 

volumes:
  pgdata:
    driver: local
